# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Markit' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Markit
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'JSQMessagesViewController'
  pod 'SwiftyJSON', '3.0.0'
  pod 'MARKRangeSlider'
  pod 'MLPAutoCompleteTextField'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

end
